export const FETCH_ALL_MEETINGS = 'FETCH_ALL_MEETINGS';
export const SAVE_FILTER = 'SAVE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';

export const FILTER_OPEN_MEETINGS = 'FILTER_OPEN_MEETINGS';
export const FILTER_CLOSED_MEETINGS = 'FILTER_CLOSED_MEETINGS';
export const FILTER_STEP_MEETINGS = 'FILTER_STEP_MEETINGS';
export const FILTER_HOUR_MEETINGS = 'FILTER_HOUR_MEETINGS';
export const FILTER_ACCESSIBLE_MEETINGS = 'FILTER_ACCESSIBLE_MEETINGS';
